services:
  backend:
    build:
      context: ../backend
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/AccountKey.json
    volumes:
      - ../backend/AccountKey.json:/app/AccountKey.json:ro

  frontend:
    build:
      context: ../frontend-vue
    ports:
      - "5173:5173"
    depends_on:
      - backend
